# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: serverlessmahin
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: crisis-desk-ai
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless

build:
  esbuild: false # keep esbuild false. we have to use serverless-esbuild for monorepo structure

provider:
  name: aws
  runtime: nodejs24.x
  region: ap-south-1

  environment:
    # pass environment variables during deploying
    NODE_OPTIONS: --enable-source-maps
    NODE_ENV: production
  apiGateway:
    shouldStartNameWithService: true
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

  iam:
    role:
      name: serverless-crsdskai-ssm-role-dev
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action: 
          - "ssm:GetParameter"
          - "ssm:GetParameters"
          - "ssm:GetParametersByPath"
          - "ssm:GetParameterHistory"
          - "ssm:DescribeParameters"

functions:
  api:
    handler: src/server.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    format: 'esm'
    outputFileExtension: '.mjs' 
    exclude: ['aws-sdk']
    platform: 'node'
    banner:
      js: |
        import { createRequire as topLevelCreateRequire } from 'module';
        const require = topLevelCreateRequire(import.meta.url);
