# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: serverlessmahin
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: crisis-desk-ai
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless
useDotenv: true

provider:
  name: aws
  runtime: nodejs24.x
  region: ap-south-1

  environment:
    # pass environment variables during deploying
    NODE_OPTIONS: --enable-source-maps
    NODE_ENV: production
    DATABASE_URL: ${env:DATABASE_URL}
    GROQ_AI_API_KEY: ${env:GROQ_AI_API_KEY}
    JWT_ACCESS_TOKEN_SECRET: ${env:JWT_ACCESS_TOKEN_SECRET}
    JWT_REFRESH_TOKEN_SECRET: ${env:JWT_REFRESH_TOKEN_SECRET}
    AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY : ${env:AWS_SECRET_ACCESS_KEY}
    MCP_BASE_URL: ${env:MCP_BASE_URL}
  apiGateway:
    shouldStartNameWithService: true
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

functions:
  api:
    handler: src/server.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline

custom:
  dotenv:
    exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY 
      - JWT_ACCESS_TOKEN_SECRET
      - JWT_REFRESH_TOKEN_SECRET
      - GROQ_AI_API_KEY
      - DATABASE_URL
